package edu.webdev.catalog.controllers;

import java.util.Map;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import edu.webdev.catalog.infrastructure.security.SecurityService;
import edu.webdev.catalog.infrastructure.security.profile.Email;
import edu.webdev.catalog.infrastructure.security.profile.Password;
import edu.webdev.catalog.infrastructure.security.profile.UserProfile;

// Specific authentication exceptions for more granular handling (kept as they handle service exceptions)
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.DisabledException;
import org.springframework.security.authentication.LockedException;
import org.springframework.security.core.AuthenticationException;

// Import Lombok's RequiredArgsConstructor (for constructor injection)
import lombok.RequiredArgsConstructor;


/**
 * Controller for managing service registrations and handling user authentication/registration.
 * The registry map and SecurityService are injected by Spring using Lombok.
 * Accepts JSON request bodies as Map.
 * Does NOT perform explicit input validation within the controller.
 * Uses UserProfile.builder() for creating UserProfile instances.
 */
@RestController
@RequestMapping("/registry")
@RequiredArgsConstructor // Lombok annotation for constructor injection of final fields
public class RegistryController {

    // The service registry map will be injected by Spring because it's final
    private final Map<String, String> services;

    // The SecurityService will be injected by Spring because it's final
    private final SecurityService securityService;

    // The constructor is generated by Lombok's @RequiredArgsConstructor

    // --- Service Registry Endpoints ---

    /**
     * Registers a new service with a given name and URL provided in a JSON request body (as a Map).
     * No explicit validation in the controller.
     *
     * @param requestBody The JSON request body automatically mapped to a Map, expected keys: "name", "url".
     * @return A ResponseEntity:
     * - 200 OK with a success message in JSON if registered.
     * - 409 CONFLICT with an error message in JSON if the service name already exists.
     * - Potentially 500 Internal Server Error if downstream processing fails.
     */
    @PostMapping("/register")
    public ResponseEntity<Map<String, String>> register(@RequestBody Map<String, String> requestBody) {
        // Safely get values from the map - does not validate presence or format
        String name = requestBody != null ? requestBody.get("name") : null;
        String url = requestBody != null ? requestBody.get("url") : null;

        if (services.containsKey(name)) {
            return ResponseEntity.status(HttpStatus.CONFLICT)
                                 .body(Map.of("error", "Service '" + name + "' is already registered."));
        }

        services.put(name, url);
        return ResponseEntity.ok(Map.of("message", "Registered " + name + " at " + url));
    }

    /**
     * Retrieves a list of all registered services.
     *
     * @return A ResponseEntity containing a JSON map of all registered service names and their URLs.
     */
    @GetMapping
    public ResponseEntity<Map<String, String>> listServices() {
        return ResponseEntity.ok(services);
    }

    /**
     * Retrieves the URL of a registered service by its name.
     *
     * @param name The name of the service to retrieve, provided as a path variable.
     * @return A ResponseEntity containing:
     * - 200 OK with the service details (name and url) in JSON if found.
     * - 404 NOT FOUND with an error message in JSON if the service does not exist.
     */
    @GetMapping("/{name}")
    public ResponseEntity<Map<String, String>> getService(@PathVariable String name) {
        String url = services.get(name);
        if (url == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                                 .body(Map.of("error", "Service '" + name + "' not found."));
        }
        return ResponseEntity.ok(Map.of("name", name, "url", url));
    }

    /**
     * Removes a registered service by its name.
     *
     * @param name The name of the service to remove, provided as a path variable.
     * @return A ResponseEntity indicating the result of the removal:
     * - 200 OK with a success message in JSON if removed.
     * - 404 NOT FOUND with an error message in JSON if the service does not exist.
     */
    @DeleteMapping("/{name}")
    public ResponseEntity<Map<String, String>> removeService(@PathVariable String name) {
        String removedUrl = services.remove(name);
        if (removedUrl == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                                 .body(Map.of("error", "Service '" + name + "' not found."));
        }
        return ResponseEntity.ok(Map.of("message", "Removed " + name, "url", removedUrl));
    }

    /**
     * Handles user registration. Maps to /registry/signup.
     * Accepts JSON request body as a Map. No explicit validation in the controller.
     * Uses UserProfile.builder() to create the UserProfile object.
     *
     * @param requestBody The JSON request body automatically mapped to a Map, expected keys: "email", "password", (optionally other profile fields).
     * @return A ResponseEntity indicating success or failure with a JSON body.
     * - 201 Created on success.
     * - Potentially 400 Bad Request or 500 Internal Server Error if downstream processing/validation fails.
     * - Potentially 409 Conflict if user already exists (handled by securityService).
     */
    @PostMapping("/signup")
    public ResponseEntity<Map<String, String>> signUp(@RequestBody Map<String, String> requestBody) {
        // Safely get values from the map - does not validate presence or format
        String emailString = requestBody != null ? requestBody.get("email") : null;
        String passwordString = requestBody != null ? requestBody.get("password") : null;

        UserProfile newUserProfile;
        try {
            // Manually create profile objects from strings received in the map.
            // Relying on these constructors/factory methods to handle potential format issues.
            Email email = Email.safeCreate(emailString)
                                 .orElseThrow(() -> new IllegalArgumentException("Invalid email format provided.")); // Example: throw if format is bad

            Password password = Password.create(passwordString); // Assuming create handles null/empty or bad format

            // Using UserProfile.builder() as the UserProfile class
            newUserProfile = UserProfile.builder()
                                        .email(email)
                                        .password(password)
                                        .build();

        } catch (IllegalArgumentException e) {
            // Catch specific exceptions thrown by profile object creation (e.g., invalid format)
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("error", e.getMessage()));
        } catch (Exception e) {
            // Catch any other unexpected exceptions during profile object creation
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(Map.of("error", "An unexpected error occurred processing signup data."));
        }


        try {
            securityService.signUp(newUserProfile);
        } catch (IllegalArgumentException e) {
             // Handle duplicate user registration or other specific issues thrown by securityService.signUp
             return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("error", e.getMessage()));
        } catch (Exception e) {
            // Catch any other unexpected exceptions during the sign-up process from securityService.signUp
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(Map.of("error", "An unexpected error occurred during signup."));
        }

        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message", "User registered successfully"));
    }

    /**
     * Handles user authentication (sign-in). Maps to /registry/signin.
     * Accepts JSON request body as a Map. No explicit validation in the controller.
     *
     * @param requestBody The JSON request body automatically mapped to a Map, expected keys: "email", "password".
     * @return A ResponseEntity with the JWT token upon successful authentication (as a Map).
     * - 200 OK with token on success.
     * - 401 Unauthorized for invalid credentials or other authentication issues.
     * - 403 Forbidden for disabled or locked accounts.
     * - Potentially 400 Bad Request or 500 Internal Server Error if downstream processing/validation fails.
     */
    @PostMapping("/signin")
    public ResponseEntity<Map<String, String>> signIn(@RequestBody Map<String, String> requestBody) {
        // Safely get values from the map - does not validate presence or format
        String emailString = requestBody != null ? requestBody.get("email") : null;
        String passwordString = requestBody != null ? requestBody.get("password") : null;
        Email email;
        Password password;
        try {
             // Manually create profile objects from strings.
             // Relying on these constructors/factory methods to handle potential format issues.
             email = Email.safeCreate(emailString)
                           .orElseThrow(() -> new IllegalArgumentException("Invalid email format provided.")); // Example: throw if format is bad
             password = Password.create(passwordString); // Assuming create handles null/empty or bad format

         } catch (IllegalArgumentException e) {
             // Handles exceptions from Email.safeCreate or Password.create due to format issues
             return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Map.of("error", e.getMessage()));
         } catch (Exception e) {
              return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(Map.of("error", "Error processing signin data."));
         }

        String jwtToken;
        try {
            jwtToken = securityService.signIn(email, password);
        } catch (BadCredentialsException e) {
             return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error", "Authentication failed: Invalid credentials"));
        } catch (DisabledException e) {
             return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error", "Authentication failed: Account is disabled"));
        } catch (LockedException e) {
             return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error", "Authentication failed: Account is locked"));
        } catch (AuthenticationException e) {
             // Catch other Spring Security AuthenticationExceptions not specifically handled above
             return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("error", "Authentication failed."));
        } catch (Exception e) {
            // Catch any other unexpected exceptions during the sign-in process from securityService.signIn
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(Map.of("error", "An unexpected internal server error occurred during authentication.")); // Corrected typo here
        }

        return ResponseEntity.ok(Map.of("token", jwtToken));
    }
}
