# Stage 1 — Build with dependencies
FROM python:3.13-alpine AS builder

WORKDIR /app

RUN apk add --no-cache --upgrade \
    build-base \
    libffi-dev \
    musl-dev \
    gcc \
    gfortran \
    python3-dev \
    py3-pip \
    lapack-dev \
    openblas-dev

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --prefix=/install -r requirements.txt

# Stage 2 — Clean final image
FROM python:3.13-alpine

WORKDIR /app

RUN apk add --no-cache \
    libffi \
    libgcc \
    libstdc++ \
    openblas

COPY --from=builder /install /usr/local

COPY app.py .

EXPOSE 8050

CMD ["python", "app.py"]
